### ISSUE TITLE
It's inplausible to make relatively pathed Symbolic Directory links.

### ISSUE THREAD

**Issue by Karolis2011** [joshudson/Emet#2]
Due to line https://github.com/joshudson/Emet/blob/master/FileSystems/FileSystem.cs#L203
if you don't provide target hint, it just converts relative path to absolute path.
if you provide File or Directory target hint, it just fails to set native method flag for a directory link. and it just flops. 
**Suggested solution:**
After line https://github.com/joshudson/Emet/blob/master/FileSystems/FileSystem.cs#L214
adding something like this:
```csharp
if (targethint == FileType.Directory)
    flags = NativeMethods.SYMBOLIC_LINK_FLAG_DIRECTORY;
```

**Comment by joshudson** [comment]
I went ahead and merged your pull request; and then fixed the rest of the issue. Should be working now.

Thanks for testing.
