### ISSUE TITLE
[Question] Any support for Directory Junctions?

### ISSUE THREAD

**Issue by jeffward01** [joshudson/Emet#6]
Hello!

I have been following your discussions here: https://github.com/dotnet/runtime/issues/24271#issuecomment-887951893 

You are a **SUPER HERO** for doing what the dotnet-core team at Microsoft has failed to do.

I had a few questions for you:

1.) Any support or planned support for [Directory Junctions](https://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link)? 

2.) Is there a performance hit if instead of using the API's provided by Microsoft as you have, if instead we do:
````bash
> mklink [[/d] | [/h] | [/j]] <link> <target>
```` 
- [Source docs for above command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink )

My reason for asking this question is if the performance is the same... (I have doubts it is the same performance), then I can implement this feature within your library.  I do not want to implement a feature in a 'sub-par' way, I would prefer to implement the feature in a programmatic way as you have.

---

Thanks so much for being a super hero!!!!!!

**Comment by joshudson** [comment]
Calling mklink as an external process is going to pay an enormous performance it. That's why I didn't do it.

The file system enumeration should support directory junctions correctly; however there is no API to create them as Directory Junctions only exist on Windows.

**Comment by wayneyaoo** [comment]
Hey @joshudson, like @jeffward01 mentioned, I leave this message simply to say thank you! This is super useful library that should've been added to dotnet runtime... Thank you so much for the work!

**Comment by joshudson** [comment]
Creating directory junctions will never be supported however; ReadLink gained the ability to read a directory junction in 0.0.6
